org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.76
neo_version_range=[26.1.2.71,)

guideme_version=26.1.12-beta
jei_version=29.6.2.38

mod_id=asteroidmining
mod_name=Asteroid Mining
mod_license=LGPL
mod_version=26.1.2-1.0.0
mod_group_id=com.ultramega.asteroidmining
mod_authors=Ultramega
mod_description=Adds the ability to send rockets to space, mine asteroids and bring the materials back.